apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: app_of_apps/app
    repoURL: 'https://gitlab.x5.ru/DevOps/platform.git'
    targetRevision: main
  project: default